### ISSUE TITLE
从redis cluster迁移

### ISSUE THREAD

**Issue by yangzhe1991** [wandoulabs/redis-port#10]
@heroliy
> 有支持 redis cluster 迁移到codis的方法吗？貌似这个不支持

**Comment by yangzhe1991** [comment]
你是如何进行操作的？具体的命令是什么？

**Comment by spinlock** [comment]
抱歉，没有使用redis-cluster 的经验。

我有一个假设：在 redis-cluster 不发生 slot-migration 的情况下，单个 redis instance 就是普通的 redis，每个 redis instance 都可以单独挂 slave。

如果这个假设成立的话，你可以对 cluster 中的每个 instance 都起独立的 redis-port 向同一个 codis 集群迁移数据。在这个过程中，不要动 cluster 的 topo 结构。这样，数据就能完整的迁移过去了。如果假设不成立的话，我也没有别的好的方法了。
