### ISSUE TITLE
restore 出错unknown command 'slotsrestore'

### ISSUE THREAD

**Issue by ggggggggod** [wandoulabs/redis-port#11]
./bin/redis-port restore -i dump.rdb -t 127.0.0.1:6379 -n 8 
2015/10/20 16:29:06 [INFO] set ncpu = 8, parallel = 8
2015/10/20 16:29:06 [INFO] restore from 'dump.rdb' to '127.0.0.1:6379'
2015/10/20 16:29:06 [PANIC] restore command error
[error]: ERR unknown command 'slotsrestore'
[stack]: 
    1   /usr/local/codis/src/github.com/wandoulabs/redis-port/cmd/utils.go:207
            main.restoreRdbEntry
    0   /usr/local/codis/src/github.com/wandoulabs/redis-port/cmd/restore.go:102
            main.func·013
        ... ...

**Comment by spinlock** [comment]
redis-port 默认 restore to codis，所以使用 slotsrestore；

导出到普通 redis 的话，需要修改代码：
https://github.com/wandoulabs/redis-port/blob/master/cmd/utils.go#L205
把指令替换成你需要的。

**Comment by ggggggggod** [comment]
谢谢,就是这么干的

**Comment by shaobo-liu** [comment]
导出到普通 redis 的话，需要修改代码：
https://github.com/wandoulabs/redis-port/blob/master/cmd/utils.go#L205
把指令替换成你需要的。
这个要怎么改

**Comment by ioung** [comment]
@liucyao @spinlock  你好，我在用redis-port工具同步两个redis的数据的时候也遇到这个报错，尝试将
这个[文件](https://github.com/wandoulabs/redis-port/blob/master/cmd/utils.go#L205) 里面的 
`s, err := redigo.String(c.Do("slotsrestore", e.Key, ttlms, e.Value))`
改成`s, err := redigo.String(c.Do("**restore**", e.Key, ttlms, e.Value))` ,执行后还是有这样的报错：
`2016/10/11 11:14:55 [INFO] rdb file = 1077222
2016/10/11 11:14:55 [PANIC] restore command error
[error]: ERR DUMP payload version or checksum are wrong
[stack]: 
    1   /root/Applications/Go/src/github.com/wandoulabs/redis-port/cmd/utils.go:208
            main.restoreRdbEntry
    0   /root/Applications/Go/src/github.com/wandoulabs/redis-port/cmd/sync.go:212
            main.(*cmdSync).SyncRDBFile.func1.1
        ... ...
`
请问你是怎么解决的呢？
