### ISSUE TITLE
Target key is busy

### ISSUE THREAD

**Issue by left2right** [wandoulabs/redis-port#12]
迁移数据从codis到redis时，报错 panic Ｔarget key is busy，请问这是什么原因，怎么解决？谢谢

**Comment by spinlock** [comment]
首先，你改了 redis-port ? 用的 restore 指令？如果是那样的话，你需要在 restore 指令前先发送一个 del 指令，具体的原因 http://redis.io/commands/restore 里面提到了，restore 不会自动覆盖。

**Comment by spinlock** [comment]
或者 redis 3.0 之后增加 REPLACE 参数

**Comment by left2right** [comment]
嗯，是用的restore，多谢建议
