### ISSUE TITLE
redis-port执行抛错utils.go:106

### ISSUE THREAD

**Issue by kewaike** [wandoulabs/redis-port#15]
go get 下载redis-port，make编译完成后，执行dump抛错，如下：
[root@ redis-port]# ./bin/redis-port dump -f 192.168.0.1:19000 -o data/IP-0-1.rdb
2015/12/11 17:40:08 [INFO] set ncpu = 1, parallel = 1
2015/12/11 17:40:08 [INFO] dump from '192.168.0.1:19000' to 'data/IP-0-1.rdb'
2015/12/11 17:40:08 [PANIC] read sync response = ''
[error]: EOF
[stack]: 
    0   /usr/local/go/gocode/src/github.com/wandoulabs/redis-port/cmd/utils.go:106
            main.func路025
        ... ...
[root@ redis-port]#

**Comment by spinlock** [comment]
从你的 panic 结果上来看，是被 redis 直接关掉了连接。所以请检查一下 redis 的日志，是不是允许 psync 或者 sync 指令，
