### ISSUE TITLE
同步时，在rdb文件传输时，如果有很大的key，超过了ReadBufferSize 会出什么问题？

### ISSUE THREAD

**Issue by foolish-boy** [wandoulabs/redis-port#16]
如题～

**Comment by spinlock** [comment]
你可以出问题的时候再来提 :smile: 

不过你要是往 codis 里灌数据，尽量不要有太大的 key，因为太大的 key-value 不符合 codis 使用场景。会带来很大的麻烦。

**Comment by spinlock** [comment]
另外，这个 buf 只是套在 socket 上加速 IO 的，对 redis 协议解析是透明的，太大太小都没有影响。
