### ISSUE TITLE
sync.go里247～252行的作用是什么？

### ISSUE THREAD

**Issue by foolish-boy** [wandoulabs/redis-port#17]
下面的代码为了做什么？清空buffer ?
go func() {
		p := make([]byte, ReaderBufferSize)
		for {
			iocopy(c, ioutil.Discard, p, len(p))
		}
	}()

**Comment by spinlock** [comment]
忽略所有指令的 response

**Comment by foolish-boy** [comment]
哦， 这样啊~ 我屏蔽了这些代码，也没发现什么问题啊。这response会扰乱数据吗 ？

**Comment by spinlock** [comment]
你注释了这些代码会出错。还是不要随便注释了吧。
