### ISSUE TITLE
-ERR Unable to perform background save

### ISSUE THREAD

**Issue by yuruli2058** [wandoulabs/redis-port#4]
2015/07/15 15:21:33 [panic]: invalid sync response, rsp = '-ERR Unable to perform background save
'
        /home/go/src/github.com/wandoulabs/codis/ext/redis-port/cmd/utils.go:103
                github.com/wandoulabs/codis/ext/redis-port/cmd.func·016

**Comment by spinlock** [comment]
Please google "redis" + "ERR Unable to perform background save". :smile:

**Comment by yuruli2058** [comment]
ok
