### ISSUE TITLE
redis-port 导入数据时出错

### ISSUE THREAD

**Issue by goldlife1981** [wandoulabs/redis-port#5]
rdb文件有800m，使用下面参数导入， 前面是的redi ，后面的codis-proxy

帮我看下是什么原因导致的。

2015/07/15 16:32:13 [INFO] total=758189300 -    168525824 [ 22%]  entry=481532      
2015/07/15 16:32:14 [INFO] total=758189300 -    168525824 [ 22%]  entry=481532      
2015/07/15 16:32:14 [PANIC] parse rdb entry error
\[error\]: EOF
    7   /home/test/op_tools/src/github.com/wandoulabs/redis-port/pkg/rdb/reader.go:75
            github.com/wandoulabs/redis-port/pkg/rdb.(*rdbReader).Read
    6   /usr/local/go/src/io/io.go:298
            io.ReadAtLeast
    5   /usr/local/go/src/io/io.go:316
            io.ReadFull
    4   /home/test/op_tools/src/github.com/wandoulabs/redis-port/pkg/rdb/reader.go:234
            github.com/wandoulabs/redis-port/pkg/rdb.(*rdbReader).readFull
    3   /home/test/op_tools/src/github.com/wandoulabs/redis-port/pkg/rdb/reader.go:240
            github.com/wandoulabs/redis-port/pkg/rdb.(*rdbReader).readBytes
    2   /home/test/op_tools/src/github.com/wandoulabs/redis-port/pkg/rdb/reader.go:148
            github.com/wandoulabs/redis-port/pkg/rdb.(*rdbReader).readString
    1   /home/test/op_tools/src/github.com/wandoulabs/redis-port/pkg/rdb/loader.go:125
            github.com/wandoulabs/redis-port/pkg/rdb.(*Loader).NextBinEntry
    0   /home/test/op_tools/src/github.com/wandoulabs/redis-port/cmd/utils.go:247
            main.func·026
        ... ...
[stack]: 
    0   /home/test/op_tools/src/github.com/wandoulabs/redis-port/cmd/utils.go:248
            main.func·026
        ... ...

**Comment by spinlock** [comment]
See github.com/wandoulabs/codis/issues#323
