### ISSUE TITLE
为什么redis-port出现连不上redis的时候也要退出

### ISSUE THREAD

**Issue by cyflhn** [wandoulabs/redis-port#6]
我做了一个测试，在执行sync的时候，把redis弄挂掉，结果redis-port退出了。如果codis出现连不上zk退出还有一点点原因的话，redis-port执行数据同步的时候出现redis连接异常也要退出进程就实在无法理解了。为什么不可以在出现异常的时候仅仅打错误日志，每隔一段时间不停地尝试连接redis，不要杀掉进程了呢？

**Comment by spinlock** [comment]
redis-port 就是一个迁移工具，遇到不能处理的问题及时退出没有问题呀。

另外，redis-port 默认使用的 sync 协议，每次建立连接都是全量同步。假设第一次同步全量是 A，第二次同步全量是 B。那么 redis-port 需要在第二次同步前清空后面的 codis 以避免 B-A ≠ ∅ 带来的数据不同步。但是 codis 不支持 flushdb/flushall 。。。咋办。。。

此外，如果有需要，redis-port 支持 psync，简单的网络异常会遵循 psync 协议重试的。

**Comment by spinlock** [comment]
psync 的意思是继续上次 sync 中断的位置继续。如果发现中断太久无法继续，psync 协议会重新全量 sync，这时候 redis-port 也会退出。和上面是同一个理由。

**Comment by cyflhn** [comment]
像遇到网络异常特别是一开始建立连接的时候，以及遇到读，写超时的时候我觉得加上重试应该更加好一点吧，数据同步就应该是一次头的过程，所以我觉得中间不要有中断。如果确实出现需要进行重新sync，也可以打错误日志，是否终止同步由使用者来决定。如果遇到异常就退出，运维要抱怨死了，怪我们写的程序健壮性不够。

**Comment by yangzhe1991** [comment]
我个人觉得这个迁移工具本来就应该是运维操作的不应该是写程序的人用吧？

**Comment by yangzhe1991** [comment]
举个极端例子，网络很不靠谱，不断自动重试，redis不断sync，不断的bgsave，会卡死的……

**Comment by cyflhn** [comment]
运维人员就怕程序莫名其妙挂掉，重试的时间间隔可以控制一下，总之是否需要重新sync交给使用者就可以了，使用者能通过日志及时发现问题，及时处理，可以根据实际情况选择是否停止程序，个人觉得这样挺好。

**Comment by yangzhe1991** [comment]
离线工具怎么搞都行吧，写一个不断重试的程序 或者 写一个出错就挂的程序+一个不断重试的脚本 其实是一个意思。后者反而更可控

**Comment by spinlock** [comment]
"所以我觉得中间不要有中断"，不是 redis-port 想中断，是网络中断。**网络中断以后，redis-port 没有办法继续下去了，即便进行下去已经没有办法做到同步了，所以只能退出**。

即便不退出最后运维发现，也只能 杀掉->清空->重新同步。

而且 redis-port 退出的时候有 log。已经把错误和异常保留下来了。还有就是，如果是运维人员的需求的话，可不可以运维写两行代码 wait redis-port 的返回值。正常情况下 redis-port 用不退出，否则退出并 exit(1)，我相信运维这点技能还是有的。

此外，redis-port 支持 psync，如果强调网络中断，请使用 psync。

针对你说的重试，我需要强调一下，增加间隔重试也没有办法保证一致性。所以只能退出。我觉得大多数情况下，一致性比运维操作重要。如果运维真的想重试，请写脚本重启 redis-port

**Comment by cyflhn** [comment]
今天进行数据迁移，真的碰到退出的情况，原因是发生eof了，我看了代码，只有在恢复rdb文件的时候才使用了并发操作，这时候一旦发生错误(目标端网络问题)，进行重试不会造成数据不一致的情况吧。毕竟这时候是读取当前的rdb文件，后续的命令还没有写到rdb文件中吧。我用脚本重启同步实在是麻烦，每次同步到一般挂了，又要重新同步。

**Comment by yangzhe1991** [comment]
> 我用脚本重启同步实在是麻烦

这个应该一点也不麻烦？

**Comment by cyflhn** [comment]
我说的麻烦不是说写脚本烦 是每次同步到一半 报错 又要重新同步

**Comment by cyflhn** [comment]
我今天下午已经同步了3次 都没成功 都是eof

**Comment by yangzhe1991** [comment]
eof的原因是什么？应该不是网络不稳吧？同步目标的proxy那边有log吗？

**Comment by cyflhn** [comment]
有 broken pipe 连接目标redis报的错 我改成重试应该没问题吧，我进度来不及了

**Comment by cyflhn** [comment]
肯定tcp层面的问题，但是不是持久性的，但是这个问题必须要跨越过去啊

**Comment by spinlock** [comment]
我的建议是，先不要这么大火气。这仅仅是一个工具，而且是 free 的。

1. 如果确定是同步 rdb 的过程出现异常，你可以尝试在自己的分支上进行修复：重新建立连接，重新执行 slotsrestore 指令（或者是 restore 指令）。这种情况很少见，而且这个项目并不是主要项目，所以我们应该不会再花费人力在这种错误上了。

2. 同步 rdb 过程并发的原因是：a. redis.Do 是同步操作，所以会有 ping-pong 的开销，b. 虽然同步量很大，但是指令之间没有依赖关系。而后续指令的同步需要保证同步顺序，但是通过不同 routine 分别进行 读和写操作使得 pipeline 同步速度足够满足需要了，如果不能满足，只能说明 master 写入太快，再快的同步也没有办法。这是一点解释。

3. 如果你确定是 redis-port 到 slave 之间的同步失败的话，解释一下：broken pipe 应该是 send request 出错，eof 是 receive response 出错。无论何种错误，都是 redis-port 和 slave 之间的网络异常。我们开发这个工具的初衷是解决 twemproxy 集群迁移到到 codis 集群，跨机房的同步操作我们不建议这么做，也没有成熟的解决方案，同时也不能保证 rdb 同步完成之后，后续指令的同步不出现异常。

4. 我怀疑你是将 master 和 redis-port 之间网络环境好，而 slave 和 redis-port 之间网络环境不好。我建议，你修改一下同步方式，master  和 redis-port 之间使用 --psync 协议 + sockfile，而 redis-port 和 slave 部署在同一个机器或者机房内。这样 redis-port 内部实现了简单的 psync 协议，在 rdb 同步完成之后，有一定的容错能力，而 redis-port 和 slave 之间带宽足够大。而且，使用 sockfile 之后，消耗不了多少内存，而且能够增加从 master 的同步速度。

5. 别生气，有什么问题可以再商量。

**Comment by cyflhn** [comment]
不好意思 我没有生气啊， 我后来仔细查了一下 应该不是网络问题 我用tcpdump抓了一下包 发现在restore的时候报了Protocol error: invalid bulk length，然后tcp连接就断了。我发现是在同步一个hash值的时候报错，这个hash对应的value很长。我上传一下附件，麻烦帮忙看看，谢谢了。大家都是做技术的，希望共同进步啊。再说一遍，真的没有生气的。
![error](https://cloud.githubusercontent.com/assets/10646084/10759331/c0f6e9cc-7cf1-11e5-8d3e-ed31ab5a45eb.png)
![restore](https://cloud.githubusercontent.com/assets/10646084/10759373/dbcbbade-7cf1-11e5-8fa6-aefd26015397.png)

**Comment by cyflhn** [comment]
没有办法上传tcpdump文件，如果方便能否留下及时通讯方式，我看了redis的代码。这个报错应该是
ok = string2ll(c->querybuf+pos+1,newline-(c->querybuf+pos+1),&ll);
            if (!ok || ll < 0 || ll > 512*1024*1024) {
                addReplyError(c,"Protocol error: invalid bulk length");
                setProtocolError(c,pos);
                return REDIS_ERR;
            }
所以我怀疑是不是这个restore指令太长了
![restore1](https://cloud.githubusercontent.com/assets/10646084/10759438/3f5ace82-7cf2-11e5-897e-93c4e5b773dd.png)

麻烦尽快帮忙看下，谢谢了

**Comment by spinlock** [comment]
OK，这么看的确是了。restore 指令是对单个 key-value 的操作，value 会被压缩成 rdb dump 格式。
你提到的这种情况属于单个 value 特别大的情况，参见 https://github.com/wandoulabs/codis/issues/425。

Redis 单个 bulk bytes 限制是 512M。所以单条 restore 指令是肯定出错的。

这种情况不属于 Codis 的应用场景。所以我们也不会进行特殊处理。

如果你十分需要这种情况的话，我可以给你的建议是修改代码，在 restore 前，将数据用 https://github.com/wandoulabs/redis-port/blob/master/pkg/rdb/decoder.go 内提供的 Decoder 转成 Hash 然后逐条 HSet。

**Comment by cyflhn** [comment]
请问下 这个为什么不是codis的应用场景，如果我有很多这样的key value，那怎么办？ 我现在要把老redis的数据散列到codis集群里面，这样key应该不少。

**Comment by spinlock** [comment]
codis 主要应对的是多 key 但是单个 key 都不太大的场景。因为 codis 本质是将所有的 key 按照 hash 值分配到不同的 redis 实例中，在需要的时候能够对 key 进行迁移和重新分布。

codis 修改了 redis 实现，在里面增加了与 slot 有关的数据结构以及与 slot 迁移有关的操作。codis 在迁移的时候本质也是发送一条指令给 server-src，命令其将对应数据迁移到 server-dst 中去，迁移过程实际上也是通过 slotsrestore 完成的。

所以如果 redis-port 没有办法将数据同步到 codis 中去的话，当 codis 发生迁移时，codis 也没有办法完成将该数据从 server-src 迁移到 server-dst 的操作。同时，为了减少阻塞的的时间，codis 后面的 redis 实例在迁移过程的超时一般都设置成很小，现在的设置是3s，所以即便数据能装入单个 bulk 中，3s内保证 500M 数据迁移到目标实例中。

codis 为了保证操作的原子性，迁移实际上是按照 tag 迁移的，所以就要求有相同 tag 的数据总和不能太大。不然很容易超时。tag 的定义可以在 codis 的 doc 里面搜到。或者直接参考 twemproxy 的文档。

**Comment by cyflhn** [comment]
那如果迁移过程中超时了 那么在dashboard上能看到吗，会重试吗， 还有，像我这种场景应该怎么解决。

**Comment by Apache9** [comment]
codis的架构就决定了他处理不了单个key对应的value特别大的情况，按照我们经验，几兆大小的一个set或者list还可以忍，再大的话迁移的时候就很容易堵了，几百兆估计迁移都无法成功。如果完全不做迁移的话，这么用倒是也可以但这就失去用codis最大的意义了。

这种情况下如果想用codis，只能是修改代码。比较常见的办法是自己在代码里再做一次sharding，比如你`hashkey`对应的这个hash有1G大小，那么你把他拆成1024个小的hash，`hashkey-0`~`hashkey-1023`，那么每个hash的大小就差不多只有1M了，就可以使用codis了。具体怎么拆就需要看你自己的业务了。

谢谢

**Comment by cyflhn** [comment]
@Apache9  你说的改代码是指改哪部分的代码，改codis代理层，还是改codis redis部分的代码

**Comment by Apache9** [comment]
改你自己业务的代码。。。

**Comment by cyflhn** [comment]
我主要担心的是老数据的平滑迁移问题，新业务是不会出现这种大key-val情况的。改老业务代码代价太大了。

**Comment by Apache9** [comment]
那这个真不好办了。。。
