### ISSUE TITLE
迁移过程中失败

### ISSUE THREAD

**Issue by SamPeng87** [wandoulabs/redis-port#7]
redis源版本
redis_version:2.8.4
迁移到codis。
文件差不多有5个G

2015/09/10 12:39:00 [PANIC] parse rdb entry error
[error]: EOF
    7   /usr/local/codis/src/github.com/wandoulabs/redis-port/pkg/rdb/reader.go:75
            github.com/wandoulabs/redis-port/pkg/rdb.(*rdbReader).Read
    6   /usr/local/go/src/io/io.go:298
            io.ReadAtLeast
    5   /usr/local/go/src/io/io.go:316
            io.ReadFull
    4   /usr/local/codis/src/github.com/wandoulabs/redis-port/pkg/rdb/reader.go:234
            github.com/wandoulabs/redis-port/pkg/rdb.(*rdbReader).readFull
    3   /usr/local/codis/src/github.com/wandoulabs/redis-port/pkg/rdb/reader.go:240
            github.com/wandoulabs/redis-port/pkg/rdb.(*rdbReader).readBytes
    2   /usr/local/codis/src/github.com/wandoulabs/redis-port/pkg/rdb/reader.go:170
            github.com/wandoulabs/redis-port/pkg/rdb.(*rdbReader).readString
    1   /usr/local/codis/src/github.com/wandoulabs/redis-port/pkg/rdb/loader.go:125
            github.com/wandoulabs/redis-port/pkg/rdb.(*Loader).NextBinEntry
    0   /usr/local/codis/src/github.com/wandoulabs/redis-port/cmd/utils.go:247
            main.newRDBLoader.func1
        ... ...
[stack]:
    0   /usr/local/codis/src/github.com/wandoulabs/redis-port/cmd/utils.go:248
            main.newRDBLoader.func1

**Comment by spinlock** [comment]
在旅游 抱歉没法看这么仔细

以前有人提过一个 issue 似乎是 redis disable rdb checksum 导致的 你搜搜是不是同样问题。

**Comment by spinlock** [comment]
sorry 好像不是 redis port 也可以离线分析 rdb 你能试试看 然后看一下 log 吗？

**Comment by SamPeng87** [comment]
就是sync同步redis到codis时。每次固定到一个值的时候就解析失败了。。没有其他日志了。

**Comment by spinlock** [comment]
你这里是sync rdb 时出错的。我的建议是，你先离线 redid-port decode 运行一下确认是哪个 key 出错了。或者修改一下
port 的代码 输出更多的 log ？

5g 的 rdb 你也不会给我分析的对吧 😢

**Comment by SamPeng87** [comment]
明白了。。谢谢

**Comment by SamPeng87** [comment]
ok了。。需要设置socketfile和filesize才行。
我们的rdb可能太大了，完全走网络同步影响蛮大的。。

**Comment by SamPeng87** [comment]
2015/09/10 15:01:39 [INFO] sync rdb done
2015/09/10 15:01:39 [PANIC] encode redis resp failed
[error]: write tcp 10.171.50.3:35852->10.172.192.169:19001: write: connection reset by peer
    2   /usr/local/codis/src/github.com/wandoulabs/redis-port/pkg/redis/encoder.go:47
            github.com/wandoulabs/redis-port/pkg/redis.Encode
    1   /usr/local/codis/src/github.com/wandoulabs/redis-port/pkg/redis/encoder.go:51
            github.com/wandoulabs/redis-port/pkg/redis.MustEncode
    0   /usr/local/codis/src/github.com/wandoulabs/redis-port/cmd/sync.go:278
            main.(*cmdSync).SyncCommand.func2
        ... ...
[stack]:
    1   /usr/local/codis/src/github.com/wandoulabs/redis-port/pkg/redis/encoder.go:52
            github.com/wandoulabs/redis-port/pkg/redis.MustEncode
    0   /usr/local/codis/src/github.com/wandoulabs/redis-port/cmd/sync.go:278
            main.(*cmdSync).SyncCommand.func2
        ... ...

**Comment by SamPeng87** [comment]
继续= =！

**Comment by spinlock** [comment]
@SamPeng87 看情况是 rdb 同步成功了，但是 sync 指令失败了。可以去查看一下 proxy 的 log，应该是 proxy 收到了不支持的指令，主动关闭的连接。

从 proxy 的日志里应该能找到答案？谢谢！

**Comment by SamPeng87** [comment]
貌似是。。。 error = command <MULTI> is not allowed
那怎么过滤掉呢.这就头疼了

**Comment by spinlock** [comment]
不能提供过滤 因为 client 发出这样的指令就意味着线上有这样的需求。否则即便完成迁移也不能正常使用服务。

所以最好先排查使用了哪些不兼容的操作，先升级业务。稳定以后再考虑是否迁移到 codis 上来？
